<a href="https://colab.research.google.com/github/Skannan03/imarticus_project/blob/main/mine_vs_rock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MINE vs ROCK classification
The main objective is to classify weather the object under the water is either a MINE or an ROCK with machine learning models
The data is collected from a sonar machine with 61 columns and 207 rows


# Import The Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import xgboost as xgb

# Import The dataset

In [ ]:
df=pd.read_csv('/content/sonar.all-data.csv')
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

# EDA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0.0200  207 non-null    float64
 1   0.0371  207 non-null    float64
 2   0.0428  207 non-null    float64
 3   0.0207  207 non-null    float64
 4   0.0954  207 non-null    float64
 5   0.0986  207 non-null    float64
 6   0.1539  207 non-null    float64
 7   0.1601  207 non-null    float64
 8   0.3109  207 non-null    float64
 9   0.2111  207 non-null    float64
 10  0.1609  207 non-null    float64
 11  0.1582  207 non-null    float64
 12  0.2238  207 non-null    float64
 13  0.0645  207 non-null    float64
 14  0.0660  207 non-null    float64
 15  0.2273  207 non-null    float64
 16  0.3100  207 non-null    float64
 17  0.2999  207 non-null    float64
 18  0.5078  207 non-null    float64
 19  0.4797  207 non-null    float64
 20  0.5783  207 non-null    float64
 21  0.5071  207 non-null    float64
 22  0.

In [ ]:
df.describe()

0.0200      0.0371      0.0428      0.0207      0.0954      0.0986  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.029208    0.038443    0.043837    0.054053    0.075105    0.104599   
std      0.023038    0.033040    0.038521    0.046583    0.055669    0.059247   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013300    0.016400    0.018900    0.024450    0.037700    0.066950   
50%      0.022800    0.030800    0.034200    0.044100    0.062000    0.092100   
75%      0.035800    0.048100    0.058200    0.065700    0.101050    0.134150   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

           0.1539      0.1601      0.3109      0.2111  ...      0.0232  \
count  207.000000  207.000000  207.000000  207.000000  ...  207.000000   
mean     0.121591    0.134677    0.177361    0.208245  ...    0.016034   
std      0.061897    0.085340    0.118311    0.134741  ...    0.012027   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080600    0.080350    0.096750    0.111150  ...    0.008350   
50%      0.105600    0.111900    0.152200    0.181000  ...    0.013800   
75%      0.153050    0.169800    0.231500    0.269000  ...    0.020700   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

           0.0027      0.0065      0.0159      0.0072      0.0167      0.0180  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.013472    0.010729    0.010917    0.009300    0.008181    0.007771   
std      0.009628    0.007071    0.007310    0.007103    0.005719    0.005756   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007350    0.005050    0.005350    0.004100    0.004400    0.003700   
50%      0.011500    0.009600    0.009300    0.007500    0.006800    0.005900   
75%      0.016750    0.014900    0.014450    0.012100    0.010350    0.010350   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

           0.0084      0.0090      0.0032  
count  207.000000  207.000000  207.000000  
mean     0.007947    0.007936    0.006523  
std      0.006485    0.006196    0.005038  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003650    0.003100  
50%      0.005800    0.006300    0.005300  
75%      0.010400    0.010350    0.008550  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

# checking for null values

In [ ]:
df.isnull().sum()

0.0200    0
0.0371    0
0.0428    0
0.0207    0
0.0954    0
         ..
0.0180    0
0.0084    0
0.0090    0
0.0032    0
R         0
Length: 61, dtype: int64

# checking the skewness of data

In [ ]:
df.skew()

<ipython-input-12-9e0b1e29546f>:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.skew()


0.0200    2.122983
0.0371    2.149965
0.0428    2.645849
0.0207    3.397590
0.0954    2.020369
0.0986    1.243828
0.1539    0.977346
0.1601    1.482755
0.3109    1.654558
0.2111    1.278532
0.1609    0.980388
0.1582    0.580918
0.2238    0.730580
0.0645    1.028081
0.0660    0.761921
0.2273    0.687003
0.3100    0.648143
0.2999    0.518349
0.5078    0.282680
0.4797   -0.089670
0.5783   -0.253902
0.5071   -0.398178
0.4328   -0.605569
0.5550   -0.698045
0.6711   -0.787297
0.6415   -0.673803
0.7104   -0.625869
0.8080   -0.608543
0.6791   -0.438803
0.3857   -0.142382
0.1307    0.265875
0.2604    0.304906
0.5121    0.429747
0.7547    0.576483
0.8537    0.602241
0.8507    0.631304
0.6692    0.691936
0.6097    1.051649
0.4943    0.920842
0.2744    0.856537
0.0510    0.866684
0.2834    0.858517
0.2825    0.911296
0.4256    1.258602
0.2641    1.371554
0.1386    1.700582
0.1051    1.783552
0.1343    1.287541
0.0383    1.266425
0.0324    1.776935
0.0232    2.724246
0.0027    2.098458
0.0065    1.

In [ ]:
df['R'].value_counts()

M    111
R     96
Name: R, dtype: int64

# Encoding The Data

In [ ]:
def encode(data):
  le=LabelEncoder()
  for i in data.columns:
    if data[i].dtype=="object":
      data[i]=le.fit_transform(data[i])
  return data

In [ ]:
encode(df)

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

     0.0090  0.0032  R  
0    0.0052  0.0044  1  
1    0.0095  0.0078  1  
2    0.0040  0.0117  1  
3    0.0107  0.0094  1  
4    0.0051  0.0062  1  
..      ...     ... ..  
202  0.0193  0.0157  0  
203  0.0062  0.0067  0  
204  0.0077  0.0031  0  
205  0.0036  0.0048  0  
206  0.0061  0.0115  0  

[207 rows x 61 columns]

#Train Test Split

In [ ]:
x=df.drop(['R'],axis=1)
y=df['R']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,stratify=y,random_state=142)

#Logistic Regression

In [ ]:
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

preds_ytrain_lr=lr.predict(xtrain)
preds_ytest_lr=lr.predict(xtest)


In [ ]:
def acc_report(actual,predicted):
  acc_score=accuracy_score(actual,predicted)
  cn_matrix=confusion_matrix(actual,predicted)
  cla_report=classification_report(actual,predicted)
  print('accuracy::',acc_score)
  print(cn_matrix)
  print(cla_report)

In [ ]:
acc_report(ytrain,preds_ytrain_lr)
acc_report(ytest,preds_ytest_lr)

accuracy:: 0.806060606060606
[[73 15]
 [17 60]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82        88
           1       0.80      0.78      0.79        77

    accuracy                           0.81       165
   macro avg       0.81      0.80      0.80       165
weighted avg       0.81      0.81      0.81       165

accuracy:: 0.8333333333333334
[[20  3]
 [ 4 15]]
              precision    recall  f1-score   support

           0       0.83      0.87      0.85        23
           1       0.83      0.79      0.81        19

    accuracy                           0.83        42
   macro avg       0.83      0.83      0.83        42
weighted avg       0.83      0.83      0.83        42



#Random Forest Classifier

In [ ]:
rf=RandomForestClassifier(min_samples_split=5,random_state=123,max_depth=6,n_estimators=100)
rf.fit(xtrain,ytrain)

preds_ytrain_rf=rf.predict(xtrain)
preds_ytest_rf=rf.predict(xtest)

acc_report(ytrain,preds_ytrain_rf)
acc_report(ytest,preds_ytest_rf)


accuracy:: 1.0
[[88  0]
 [ 0 77]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        88
           1       1.00      1.00      1.00        77

    accuracy                           1.00       165
   macro avg       1.00      1.00      1.00       165
weighted avg       1.00      1.00      1.00       165

accuracy:: 0.9285714285714286
[[22  1]
 [ 2 17]]
              precision    recall  f1-score   support

           0       0.92      0.96      0.94        23
           1       0.94      0.89      0.92        19

    accuracy                           0.93        42
   macro avg       0.93      0.93      0.93        42
weighted avg       0.93      0.93      0.93        42



# Decision Tree Classifier

In [ ]:
dc=DecisionTreeClassifier(min_samples_split=5,random_state=123,max_depth=7)
dc.fit(xtrain,ytrain)

preds_ytrain_dc=dc.predict(xtrain)
preds_ytest_dc=dc.predict(xtest)

acc_report(ytrain,preds_ytrain_dc)
acc_report(ytest,preds_ytest_dc)

accuracy:: 0.9939393939393939
[[88  0]
 [ 1 76]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        88
           1       1.00      0.99      0.99        77

    accuracy                           0.99       165
   macro avg       0.99      0.99      0.99       165
weighted avg       0.99      0.99      0.99       165

accuracy:: 0.8095238095238095
[[21  2]
 [ 6 13]]
              precision    recall  f1-score   support

           0       0.78      0.91      0.84        23
           1       0.87      0.68      0.76        19

    accuracy                           0.81        42
   macro avg       0.82      0.80      0.80        42
weighted avg       0.82      0.81      0.81        42



# Gradient Boosting Classifier

In [ ]:
gb=GradientBoostingClassifier()
gb.fit(xtrain,ytrain)
preds_gb_train=gb.predict(xtrain)
preds_gb_test=gb.predict(xtest)
acc_report(ytrain,preds_gb_train)
acc_report(ytest,preds_gb_test)

accuracy:: 1.0
[[88  0]
 [ 0 77]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        88
           1       1.00      1.00      1.00        77

    accuracy                           1.00       165
   macro avg       1.00      1.00      1.00       165
weighted avg       1.00      1.00      1.00       165

accuracy:: 0.8571428571428571
[[20  3]
 [ 3 16]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87        23
           1       0.84      0.84      0.84        19

    accuracy                           0.86        42
   macro avg       0.86      0.86      0.86        42
weighted avg       0.86      0.86      0.86        42



#Conclusion

The logistic Regression performs well on this data giving the highest Accuracy score 83 percentage with low bias and low variance predicting weather it is rock or a mine